/////////////////////////////////////////////////////////////////////////////////////////////////////
//
// Audiokinetic Wwise generated include file. Do not edit.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef __WWISE_IDS_H__
#define __WWISE_IDS_H__

#include <AK/SoundEngine/Common/AkTypes.h>

namespace AK
{
    namespace EVENTS
    {
        static const AkUniqueID EVENT_FOOTSTEP = 3618206844U;
        static const AkUniqueID EVENT_JADEIDE_SLOW__PICKUP = 35105690U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ACTIF_ABSORB_CONVERT_FULL__ITEMNUMBER = 1311394723U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ACTIF_ACTIVATION__ITEMNUMBER = 3519253650U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ACTIF_ATTACK_FULL__ITEMNUMBER = 3848766526U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ACTIF_BASE1__ITEMNUMBER = 2795927674U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ACTIF_BASE2__ITEMNUMBER = 2786944721U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ACTIF_HOLDING__ITEMNUMBER = 3245141071U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ANNEAUX_BRAVOURE_ACTIF_ACTIVATION2__ITEMNUMBER = 971120188U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ANNEAUX_BRAVOURE_ATTACK_FULL__ITEMNUMBER = 3355272866U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ANNEAUX_BRAVOURE_ATTACK_PT1__ITEMNUMBER = 2245180070U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ANNEAUX_BRAVOURE_ATTACK_PT2__ITEMNUMBER = 48028301U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ANNEAUX_BRAVOURE_EQUIP__ITEMNUMBER = 2443778206U;
        static const AkUniqueID PLAY_ANNEAUX_BRAVOURE_ANNEAUX_BRAVOURE_PASSIF_FULL__ITEMNUMBER = 1375151096U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ACTIF_DASH__ITEMNUMBER = 2331823957U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ACTIF_FX1__ITEMNUMBER = 2129374944U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ACTIF_FX2__ITEMNUMBER = 3131559339U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ACTIF_FX3__ITEMNUMBER = 2391360038U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_CATCH_FULL_TYPE1__ITEMNUMBER = 358914239U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_CATCH_FULL_TYPE2__ITEMNUMBER = 329721332U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_CATCH_FULL_TYPE3__ITEMNUMBER = 4013114017U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_CATCH_FULL_TYPE4__ITEMNUMBER = 1743866334U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_FLYING_PART2__ITEMNUMBER = 1524339847U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_FLYING_PT1__ITEMNUMBER = 890300161U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_STAY__ITEMNUMBER = 1119473739U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_STAY_FULL_WITHSTART_END__ITEMNUMBER = 231791066U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_STAY_START__ITEMNUMBER = 1432283930U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_STAY_START_STOP__ITEMNUMBER = 611666961U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_STAY_STOP__ITEMNUMBER = 1220261050U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_THROW_TYPE1__ITEMNUMBER = 330969792U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_THROW_TYPE2__ITEMNUMBER = 1828072971U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_THROW_TYPE3__ITEMNUMBER = 1113152902U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__ATTACK_THROW_TYPE4__ITEMNUMBER = 1370043657U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__PASSIF_ACTIVE__ITEMNUMBER = 3240899460U;
        static const AkUniqueID PLAY_ANNEAUX_INTR_PIDIT__PASSIF_END__ITEMNUMBER = 1708722073U;
        static const AkUniqueID PLAY_ANNEAUX_PASSION_ANNEAUX_PASSION_ACTIF_FULL__ITEMNUMBER = 368652901U;
        static const AkUniqueID PLAY_ANNEAUX_PASSION_ANNEAUX_PASSION_ATTACK_FULL__ITEMNUMBER = 683100430U;
        static const AkUniqueID PLAY_ANNEAUX_PASSION_ANNEAUX_PASSION_ATTACK_PT1__ITEMNUMBER = 3852939954U;
        static const AkUniqueID PLAY_ANNEAUX_PASSION_ANNEAUX_PASSION_ATTACK_PT2__ITEMNUMBER = 80281929U;
        static const AkUniqueID PLAY_ANNEAUX_PASSION_ANNEAUX_PASSION_EQUIP__ITEMNUMBER = 419834130U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_ACTIF_EXPLOSION_PT1__ITEMNUMBER = 820125396U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_ACTIF_EXPLOSION_PT2__ITEMNUMBER = 1595907359U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_ATTACK_TNT_DESPAWN__ITEMNUMBER = 2569161331U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_ATTACK_TNT_WAIT__ITEMNUMBER = 647745864U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_ATTACK_TROW_IMPACT_DAMAGE__ITEMNUMBER = 2562864793U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_ATTACK_TROW_IMPACT_PLACED__ITEMNUMBER = 1211254069U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_ATTACK_TROW_PT1__ITEMNUMBER = 2835906194U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_ATTACK_TROW_PT2__ITEMNUMBER = 3058761769U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_PASSIF_ENTERRAYON__ITEMNUMBER = 468307329U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_PASSIF_INSIDE_FULL__ITEMNUMBER = 584110532U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_PASSIF_INSIDE_LOOP__ITEMNUMBER = 2340276349U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_PASSIF_INSIDE_START__ITEMNUMBER = 782609553U;
        static const AkUniqueID PLAY_ANNEAUX_PATIENCE_PASSIF_LEAVERAYON__ITEMNUMBER = 3230843872U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_PARTS_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_PT1__ITEMNUMBER = 2505770584U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_PARTS_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_PT2__ITEMNUMBER = 69287139U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_PARTS_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_PT3__ITEMNUMBER = 2375100894U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_PARTS_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_PT4__ITEMNUMBER = 349381281U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ACTIF_START_PARTS_ANNEAUX_PERSEVERENCE_ACTIF_START_PT1__ITEMNUMBER = 2350078742U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ACTIF_START_PARTS_ANNEAUX_PERSEVERENCE_ACTIF_START_PT2__ITEMNUMBER = 1083529149U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ACTIF_START_PARTS_ANNEAUX_PERSEVERENCE_ACTIF_START_PT3__ITEMNUMBER = 415217232U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ATTACK_COOLDOWN_PT1__ITEMNUMBER = 4121344809U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ATTACK_COOLDOWN_PT2__ITEMNUMBER = 3898489234U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ATTACK_COOLDOWN_PT3_DONE__ITEMNUMBER = 659293366U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ATTACK_PT1__ITEMNUMBER = 3881681859U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_ATTACK_PT2__ITEMNUMBER = 551889208U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_EQUIP_PARTS_ANNEAUX_PERSEVERENCE_EQUIP_PT1__ITEMNUMBER = 680953922U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_EQUIP_PARTS_ANNEAUX_PERSEVERENCE_EQUIP_PT2__ITEMNUMBER = 1175457881U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_EQUIP_PARTS_ANNEAUX_PERSEVERENCE_EQUIP_PT3__ITEMNUMBER = 864848364U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_EQUIP_PARTS_ANNEAUX_PERSEVERENCE_EQUIP_PT4__ITEMNUMBER = 4083119323U;
        static const AkUniqueID PLAY_ANNEAUX_PERSEVERENCE_EQUIP_PARTS_ANNEAUX_PERSEVERENCE_EQUIP_PT5__ITEMNUMBER = 831071958U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_INTR_PIDIT__ACTIF_FULL__ITEMNUMBER = 3822052572U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_INTR_PIDIT__ATTACK_BLADES_FLYING_FULL__ITEMNUMBER = 3931346177U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_INTR_PIDIT__EQUIPE_FULL__ITEMNUMBER = 1864842442U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_INTR_PIDIT__PASSIF_FULL__ITEMNUMBER = 3849067727U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PASSION_ANNEAUX_PASSION_PASSIF_FULL__ITEMNUMBER = 2624215598U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PATIENCE_ACTIF_EXPLOSION_FULL__ITEMNUMBER = 1932143882U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PATIENCE_ATTACK_TROW_FULL__ITEMNUMBER = 3146683060U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PATIENCE_ATTACK_TROW_IMPACT_FULL__ITEMNUMBER = 1427764535U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PATIENCE_EQUIPE_FULL__ITEMNUMBER = 986124536U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_ACTIF_COMPLETE_FULL__ITEMNUMBER = 1106791576U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_ACTIF_PUSH_FULL__ITEMNUMBER = 1192075387U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_ACTIF_START_FULL__ITEMNUMBER = 77499785U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_ATTACK_COLDOWN_FULL__ITEMNUMBER = 1894354718U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_ATTACK_COMPLETE_2SEC_FULL__ITEMNUMBER = 3515088067U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_ATTACK_COMPLETE_3SEC_FULL__ITEMNUMBER = 3461245946U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_ATTACK_NORMAL_FULL__ITEMNUMBER = 3190605359U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_ATTACK_TIR_FULL__ITEMNUMBER = 4271747987U;
        static const AkUniqueID PLAY_FULL_ANNEAUX_PERSEVERENCE_EQUIP_FULL__ITEMNUMBER = 952051097U;
        static const AkUniqueID PLAY_MUSIQUE_COMBAT_FULL_ONETIME__ITEMNUMBER = 54626728U;
        static const AkUniqueID PLAY_MUSIQUE_COMBAT_LOOP__ITEMNUMBER = 227535219U;
        static const AkUniqueID PLAY_MUSIQUE_LOBBY_FULL_ONETIME__ITEMNUMBER = 699954836U;
        static const AkUniqueID PLAY_MUSIQUE_LOBBY_LOOP__ITEMNUMBER = 2547827055U;
        static const AkUniqueID PLAY_MUSIQUE_LOBBY_START__ITEMNUMBER = 3229792879U;
        static const AkUniqueID PLAY_MUSIQUE_MENU_LOOP__ITEMNUMBER = 4142008756U;
    } // namespace EVENTS

    namespace SWITCHES
    {
        namespace FOOTSTEPS
        {
            static const AkUniqueID GROUP = 2385628198U;

            namespace SWITCH
            {
                static const AkUniqueID STONE = 1216965916U;
            } // namespace SWITCH
        } // namespace FOOTSTEPS

    } // namespace SWITCHES

    namespace BANKS
    {
        static const AkUniqueID INIT = 1355168291U;
        static const AkUniqueID SOUNDBANK_ANNEAUX_BRAVOURE = 2084984678U;
        static const AkUniqueID SOUNDBANK_ANNEAUX_INTREPIDITE = 3887377697U;
        static const AkUniqueID SOUNDBANK_ANNEAUX_PASSION = 4293030339U;
        static const AkUniqueID SOUNDBANK_ANNEAUX_PATIENCE = 467007289U;
        static const AkUniqueID SOUNDBANK_ANNEAUX_PERSEVERENCE = 381671057U;
        static const AkUniqueID SOUNDBANK_GEMME_JADEITE_PICKUP = 2811913676U;
        static const AkUniqueID SOUNDBANK_MOVEMENT = 486013808U;
        static const AkUniqueID SOUNDBANK_MUSIQUE = 831985312U;
    } // namespace BANKS

    namespace BUSSES
    {
        static const AkUniqueID MASTER_AUDIO_BUS = 3803692087U;
    } // namespace BUSSES

    namespace AUDIO_DEVICES
    {
        static const AkUniqueID NO_OUTPUT = 2317455096U;
        static const AkUniqueID SYSTEM = 3859886410U;
    } // namespace AUDIO_DEVICES

}// namespace AK

#endif // __WWISE_IDS_H__
